language: Swift
osx_image: xcode9.3
xcode_project: CoreEvents/CoreEvents.xcodeproj # path to your xcodeproj folder
xcode_scheme: CoreEvents
before_install:
  - gem install xcpretty -N
  - brew update
  - brew install swiftlint || true
script:
  - set -o pipefail
  - xcodebuild test -project CoreEvents/CoreEvents.xcodeproj -scheme CoreEventsTests -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO -enableCodeCoverage YES -destination 'platform=iOS Simulator,name=iPhone 8,OS=11.1' | xcpretty -c
